"""
Property-based tests for JWT token functionality.

Feature: fastapi-prisma-migration
"""

import pytest
from hypothesis import given, strategies as st, settings as hypothesis_settings
from jose import jwt, JWTError
from services.auth import create_access_token, decode_access_token
from config import settings


# Feature: fastapi-prisma-migration, Property 3: JWT Token Signature Validity
@given(email=st.emails())
@hypothesis_settings(max_examples=100)
def test_jwt_token_signature_validity(email):
    """
    Property 3: JWT Token Signature Validity
    
    For any JWT token generated by the system, decoding it with the 
    configured secret key should successfully return the token payload; 
    tokens signed with a different key should fail validation.
    
    Validates: Requirements 9.2
    """
    # Create a token with the user's email
    token = create_access_token(data={"sub": email})
    
    # Decoding with correct secret should succeed
    token_data = decode_access_token(token)
    assert token_data is not None
    assert token_data.email == email
    
    # Decoding with wrong secret should fail
    try:
        wrong_payload = jwt.decode(token, "wrong_secret_key_12345", algorithms=[settings.algorithm])
        # If we get here, the test should fail
        assert False, "Token should not decode with wrong secret"
    except JWTError:
        # Expected behavior - token fails with wrong secret
        pass



# Feature: fastapi-prisma-migration, Property 4: JWT Token Contains User Identity
@given(email=st.emails())
@hypothesis_settings(max_examples=100)
def test_jwt_token_contains_user_identity(email):
    """
    Property 4: JWT Token Contains User Identity
    
    For any user who successfully logs in, the generated JWT token should 
    contain the user's email in the payload (as the "sub" claim).
    
    Validates: Requirements 9.3
    """
    # Create a token with the user's email
    token = create_access_token(data={"sub": email})
    
    # Decode the token and verify it contains the email
    token_data = decode_access_token(token)
    assert token_data is not None
    assert token_data.email == email
    
    # Also verify by directly decoding the JWT
    payload = jwt.decode(token, settings.secret_key, algorithms=[settings.algorithm])
    assert payload.get("sub") == email



# Feature: fastapi-prisma-migration, Property 5: Expired Token Rejection
@given(email=st.emails())
@hypothesis_settings(max_examples=100)
def test_expired_token_rejection(email):
    """
    Property 5: Expired Token Rejection
    
    For any JWT token that has passed its expiration time, authentication 
    attempts using that token should be rejected with 401 Unauthorized status.
    
    Validates: Requirements 9.5
    """
    from datetime import timedelta
    
    # Create a token that expires immediately (negative expiration)
    expired_token = create_access_token(
        data={"sub": email},
        expires_delta=timedelta(seconds=-1)  # Already expired
    )
    
    # Attempting to decode an expired token should return None
    token_data = decode_access_token(expired_token)
    assert token_data is None
    
    # Directly decoding should raise JWTError
    try:
        jwt.decode(expired_token, settings.secret_key, algorithms=[settings.algorithm])
        # If we get here, the test should fail
        assert False, "Expired token should not decode successfully"
    except JWTError:
        # Expected behavior - expired token raises error
        pass
